version: '3.8'

services:
  lots-versequest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lots-versequest
    image: lots-versequest:latest
    ports:
      - "3001:80"
    restart: always